# Generated by Django 5.2 on 2025-06-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reporte",
            name="titulo",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
