# Generated by Django 5.2 on 2025-06-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0002_juego_valoracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='name',
        ),
        migrations.AlterField(
            model_name='juego',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
