# Generated by Django 5.2 on 2025-06-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0003_remove_juego_name_alter_juego_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracion',
            name='valor',
            field=models.FloatField(),
        ),
    ]
