# Generated by Django 5.2 on 2025-06-05 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0004_alter_valoracion_valor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteca',
            name='estado',
            field=models.CharField(choices=[('jugando', 'Jugando'), ('completado', 'Completado'), ('abandonado', 'Abandonado'), ('en_espera', 'En espera')], default='jugando', max_length=20),
        ),
        migrations.CreateModel(
            name='Planificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('juegos', models.ManyToManyField(related_name='planificaciones', to='juegos.juego')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
