# Generated by Django 5.2 on 2026-02-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0008_planificacioncompletada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblioteca',
            name='game_id',
            field=models.BigIntegerField(),
        ),
    ]
