# Generated by Django 5.2 on 2026-02-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0009_biblioteca_game_id_bigint'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='aggregated_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='juego',
            name='cover_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='juego',
            name='first_release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='juego',
            name='genres',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='juego',
            name='involved_companies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='juego',
            name='name',
            field=models.CharField(db_index=True, default='Unknown Game', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juego',
            name='platforms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='juego',
            name='popularidad',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='juego',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='juego',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='juego',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='juego',
            name='themes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='juego',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
