# Generated by Django 5.2 on 2025-06-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0007_perfil_bloqueados_perfil_seguidores"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="gustos_generos",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
