# Generated by Django 5.2 on 2025-06-05 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_perfil_gustos_generos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='gustos_generos',
        ),
    ]
