# Generated by Django 5.2 on 2025-06-05 09:01

import django.db.models.deletion
import juegos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0005_biblioteca_estado_planificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='planificacion',
            name='duracion_jugada',
            field=models.DurationField(default=juegos.models.default_duration),
        ),
        migrations.AddField(
            model_name='planificacion',
            name='duracion_total',
            field=models.DurationField(default=juegos.models.default_duration),
        ),
        migrations.CreateModel(
            name='DuracionJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion_main', models.DurationField(blank=True, null=True)),
                ('fecha_consulta', models.DateTimeField(auto_now=True)),
                ('juego', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='duracion_juego', to='juegos.juego')),
            ],
        ),
    ]
