# Generated by Django 5.2 on 2025-06-06 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comentarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comentario",
            options={
                "ordering": ["-fecha"],
                "permissions": [("ver_comentarios", "Puede ver todos los comentarios")],
            },
        ),
    ]
