# Generated by Django 5.2 on 2025-05-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_perfil_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='filtro_adulto',
            field=models.BooleanField(default=True),
        ),
    ]
