# Generated by Django 5.2 on 2025-05-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_perfil_filtro_adulto'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='favoritos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
