# Generated by Django 5.2 on 2025-06-03 10:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_perfil_favoritos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='bloqueados',
            field=models.ManyToManyField(blank=True, related_name='bloqueados_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perfil',
            name='seguidores',
            field=models.ManyToManyField(blank=True, related_name='seguidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
