# Generated by Django 5.2 on 2025-06-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_remove_perfil_gustos_generos'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='gustos_generos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
