# Generated by Django 5.2 on 2025-06-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0010_perfil_gustos_generos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="rol",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrador"),
                    ("DEV", "Desarrollador"),
                    ("STAFF", "Staff"),
                    ("REVIEWER", "Revisor"),
                    ("PLAYER", "Jugador"),
                ],
                default="PLAYER",
                max_length=10,
            ),
        ),
    ]
