# Generated by Django 5.2 on 2025-06-09 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0012_alter_perfil_rol"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="tiempo_total",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
