# Generated by Django 5.2 on 2025-06-04 08:50

import django.db.models.deletion
import django.utils.timezone
import sesiones.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('juegos', '0004_alter_valoracion_valor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='juegos.juego')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='TiempoJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion_total', models.DurationField(default=sesiones.models.default_duration)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiempos_juego', to='juegos.juego')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiempos_juego', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'juego')},
            },
        ),
    ]
