# Generated by Django 5.2 on 2025-06-03 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('juegos', '0004_alter_valoracion_valor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('duracion', models.DurationField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('jugando', 'Jugando'), ('completado', 'Completado'), ('abandonado', 'Abandonado'), ('en_espera', 'En espera')], default='jugando', max_length=20)),
                ('nota', models.TextField(blank=True)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas_diario', to='juegos.juego')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas_diario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
